import 'package:flutter/material.dart';
import 'package:flutter_ladvet/models/pet.dart';

class MockupPets {
  static const List<Pet> pets = [
    Pet(
      id: 1,
      nome: 'Tulipa',
      idade: '10 anos',
      especie: 'Canino',
      sexo: 'Fêmea',
      vacinas: 'Todas em dia',
      temperamento: 'Calma e carinhosa',
      descricao: 'Tulipa é uma cachorrinha dócil e muito carinhosa.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/tulipa.png',
    ),
    Pet(
      id: 2,
      nome: 'Thor',
      idade: '8 anos',
      especie: 'Canino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Brincalhão e protetor',
      descricao: 'Thor é um cachorro brincalhão e muito companheiro.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/thor.png',
    ),
    Pet(
      id: 3,
      nome: 'Pretinho',
      idade: '5 anos',
      especie: 'Canino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Dócil e amigável',
      descricao: 'Pretinho é tranquilo, carinhoso e gosta de companhia.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/pretinho.png',
    ),
    Pet(
      id: 4,
      nome: 'Nina',
      idade: '3 anos',
      especie: 'Canino',
      sexo: 'Fêmea',
      vacinas: 'Todas em dia',
      temperamento: 'Brincalhona e dócil',
      descricao: 'Nina é uma cachorrinha alegre que adora brincar.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/nina.png',
    ),
    Pet(
      id: 5,
      nome: 'Meggie',
      idade: '8 anos',
      especie: 'Canino',
      sexo: 'Fêmea',
      vacinas: 'Todas em dia',
      temperamento: 'Calma e carinhosa',
      descricao: 'Meggie é tranquila, carinhosa e gosta de receber atenção.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/meggie.png',
    ),
    Pet(
      id: 6,
      nome: 'Salsicha',
      idade: '3 anos',
      especie: 'Canino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Energético e brincalhão',
      descricao: 'Salsicha é muito divertido, ativo e adora brincar.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/salsicha.jpg',
    ),
    Pet(
      id: 7,
      nome: 'Duck',
      idade: '2 anos',
      especie: 'Felino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Curioso e brincalhão',
      descricao: 'Duck é um gato curioso que gosta de explorar novos lugares.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/duck.png',
    ),
    Pet(
      id: 8,
      nome: 'Fred',
      idade: '3 anos',
      especie: 'Canino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Amigável e carinhoso',
      descricao: 'Fred é um cachorro amigável e muito companheiro.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/fred.png',
    ),
    Pet(
      id: 9,
      nome: 'Jady',
      idade: '4 anos',
      especie: 'Canino',
      sexo: 'Fêmea',
      vacinas: 'Todas em dia',
      temperamento: 'Dócil e brincalhona',
      descricao: 'Jady é carinhosa, alegre e gosta de brincar.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/jady.png',
    ),
    Pet(
      id: 10,
      nome: 'Theo',
      idade: '2 anos',
      especie: 'Felino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Calmo e curioso',
      descricao: 'Theo é um gatinho tranquilo e muito curioso.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/theo.png',
    ),
    Pet(
      id: 11,
      nome: 'Aurora',
      idade: '1 ano',
      especie: 'Felino',
      sexo: 'Fêmea',
      vacinas: 'Todas em dia',
      temperamento: 'Carinhosa e brincalhona',
      descricao: 'Aurora é uma gatinha jovem, carinhosa e cheia de energia.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/aurora.jpg',
    ),
    Pet(
      id: 12,
      nome: 'Romeu',
      idade: '1 ano',
      especie: 'Felino',
      sexo: 'Macho',
      vacinas: 'Todas em dia',
      temperamento: 'Dócil e carinhoso',
      descricao: 'Romeu é um gatinho dócil que adora receber carinho.',
      status: 'Disponível',
      icon: Icons.pets,
      imagePath: 'assets/romeu.jpg',
    ),
  ];
}
