name: Publicar LADVET

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publicar:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Baixar arquivos do projeto
        uses: actions/checkout@v6

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Montar site
        run: |
          mkdir site
          cp -r web/html/* site/
          cp -r web/css site/
          cp -r web/js site/
          cp -r web/img site/

      - name: Enviar site
        uses: actions/upload-pages-artifact@v4
        with:
          path: './site'

      - name: Publicar site
        id: deployment
        uses: actions/deploy-pages@v4
